Description: >
  cloudformation to generate some new resources in our app runner open ai
Parameters:
  BucketMainName:
    Type: String
    Default: my-main-files-bucket
    Description: provide a name the source bucket
Resources:
  MainBucketBackupRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
  MainBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Ref BucketMainName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
      ReplicationConfiguration:
        Role: !GetAtt
          - MainBucketBackupRole
          - Arn
        Rules:
          - Destination:
              Bucket: !ImportValue 'doc-classification-bucket-arn'
              StorageClass: STANDARD
            Id: ClassificationBucket
            Prefix: ''
            Status: Enabled
  BucketMainPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetReplicationConfiguration'
              - 's3:ListBucket'
            Effect: Allow
            Resource: !GetAtt MainBucket.Arn
          - Action:
              - 's3:GetObjectVersion'
              - 's3:GetObjectVersionAcl'
            Effect: Allow
            Resource: !Join
              - ''
              - - !GetAtt MainBucket.Arn
                - /*
          - Action:
              - 's3:ReplicateObject'
              - 's3:ReplicateDelete'
            Effect: Allow
            Resource: !Join
              - ''
              - - !ImportValue 'doc-classification-bucket-arn'
                - /*
      PolicyName: BucketBackupPolicy
      Roles:
        - !Ref MainBucketBackupRole